"use client";
import React from "react";
import HomeComponent from "@/components/HomeComponent";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Scan QR",
	description: "Generated by NHA to deliver PMJAY Card Offline",
};

const ScanPage = () => {
	return <HomeComponent />;
};

export default ScanPage;
