"use client";
import FamilyComponent from "@/components/FamilyComponent";
import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Family Member Details",
	description: "Generated by NHA to deliver PMJAY Card Offline",
};

const FamilyDetailsPage = () => {
	return <FamilyComponent />;
};

export default FamilyDetailsPage;
